# alert types
ALERT_TYPE_TRADEYA = 1
ALERT_TYPE_OFFER = 2
ALERT_TYPE_OTHER = 3
ALERT_TYPE_COMMENT = 4
MOBILE = 1
MAIL = 2

# notification frequency
NOTIFICATION_FREQUENCY_IMMEDIATE = 1
NOTIFICATION_FREQUENCY_DAILY = 2
NOTIFICATION_FREQUENCY_WEEKLY = 3

# alert numbers
NEW_OFFER_ON_TRADEYA = 1
TRADEYA_EXPIRE_IN_24_HOUR = 2
TRADEYA_ENDING_IN_12_HOUR = 3
NEW_COMMENT_ON_TRADEYA_4_PUB = 4
TRADEYA_LIVE = 5
TRADEYA_FEATURED = 6
OFFER_EDITED = 7
OFFER_DELETED = 8
NEW_COMMENT_ON_TRADEYA_4_OFFERER = 9
OFFER_NOT_ACCEPTED = 10
OFFER_ACCEPTED = 11
OFFER_RATED = 12
TRADEYA_POSTPHONED = 13
TRADEYA_EXPIRED = 14
TRADEYA_RESUBMITTED = 15
COMMENT_ON_ITEM = 16

# alert no and partial name hash
ALERT_NO_HASH = {
    1 => "new_offer_on_tradeya",
    2 => "tradeya_expire_in_24_hour",
    3 => "tradeya_ending_in_12_hour",
    4 => "new_comment_on_tradeya_4_pub",
    5 => "tradeya_live",
    6 => "tradeya_featured",
    7 => "offer_edited",
    8 => "offer_deleted",
    9 => "new_comment_on_tradeya_4_offerer",
    10 => "offer_not_accepted",
    11 => "offer_accepted",
    12 => "offer_rated",
    13 => "tradeya_postphoned",
    14 => "tradeya_expired",
    15 => "tradeya_resubmitted",
    16 => "comment_on_item"
}

# Tool tips
TOOL_TIP_NEW_OFFER = 1
TOOL_TIP_RE_USE_OFFER = 2
TOOL_TIP_NEW_TRADEYA = 3
TOOL_TIP_POSTPONE_TRADEYA = 4
TOOL_TIP_SPREAD_THE_WORD = 5
TOOL_TIP_TIME_IS_TICKLING = 6
TOOL_TIP_RESUBMIT_POSPONED_TRADEYA = 7
TOOL_TIP_RESUBMIT_EXPIRED_TRADEYA = 8
TOOL_TIP_PUBLISHER_OFFER_1 = 9
TOOL_TIP_PUBLISHER_OFFER_2 = 10
TOOL_TIP_OFFER_PAGE = 11
TOOL_TIP_NEW_TRADEYA_RIGHT = 12
TOOL_TIP_POSTPONE_TRADEYA_RIGHT = 13
TOOL_TIP_SPREAD_THE_WORD_RIGHT = 14
TOOL_TIP_TIME_IS_TICKLING_RIGHT = 15
TOOL_TIP_RESUBMIT_EXPIRED_TRADEYA_RIGHT = 16
TOOL_TIP_RESUBMIT_POSPONED_TRADEYA_RIGHT = 17
TOOL_TIP_NEW_OFFER_RIGHT = 18
TOOL_TIP_RE_USE_OFFER_RIGHT = 19
TOOL_TIP_PUBLISHER_OFFER_1_RIGHT = 20
TOOL_TIP_PUBLISHER_OFFER_2_RIGHT = 21
TOOL_TIP_OFFER_PAGE_RIGHT = 22

# Notification TYPE
NOTIFICATION_TYPE_IMIDIATE = 1
NOTIFICATION_TYPE_USER_SETTING = 2

NOTIFICATION_CONTACT = 1
NOTIFICATION_CONTACT_PUB_COPY = 2
NOTIFICATION_TRADEYA_EXPIRE = 3
NOTIFICATION_OFFER_MADE = 4
NOTIFICATION_OFFER_ENDS_IN_24_HOUR = 5
NOTIFICATION_RATED_YOUR_ITEM = 6
NOTIFICATION_OFFER_MADE_ON_YOUR_OFFER = 7
NOTIFICATION_SOMEONE_OFFER_HIGHER_THAN_YOURS = 8
NOTIFICATION_TRADEYA_IS_LIVE = 9
NOTIFICATION_RATE_OFFER = 10
NOTIFICATION_SEE_COMMENT = 11
NOTIFICATION_SEE_PUB_COMMENT = 12
NOTIFICATION_CONTACT_ALL = 13
NOTIFICATION_TRADEYA_POSTPONED = 14
NOTIFICATION_TRADEYA_RESUMED = 15
NOTIFICATION_YOUR_ACCOUNT_DEACTIVATED = 16
NOTIFICATION_OFFER_ON_TRADEYA_EDITED = 17
NOTIFICATION_OFFER_ON_TRADEYA_DELETED = 18
NOTIFICATION_OFFER_ACCEPTED = 19
NOTIFICATION_TRADEYA_COMPLETED = 20
NOTIFICATION_TRADEYA_POSTPONED_PUB = 21
NOTIFICATION_TRADEYA_REACTIVATED = 22
NOTIFICATION_WRITE_REVIEW = 23
NOTIFICATION_CATEGORY_MATCH = 24
NOTIFICATION_PERSON_MATCH = 25
NOTIFICATION_CONTEST_EMAIL = 26
NOTIFICATION_GUEST_UPGRADE_REMINDER = 27
NOTIFICATION_GUEST_FINAL_REMINDER = 28
NOTIFICATION_GUEST_FAREWELL = 29
NOTIFICATION_MOVING_ON = 30
NOTIFICATION_REQUEST_INFO = 31

NOTIFICATION_NO_DESC_HASH = {
    1 => "CONTACT",
    2 => "CONTACT_PUB_COPY",
    3 => "TRADEYA_EXPIRE",
    4 => "OFFER_MADE",
    5 => "OFFER_ENDS_IN_24_HOUR",
    6 => "RATED_YOUR_ITEM",
    7 => "OFFER_MADE_ON_YOUR_OFFER",
    8 => "SOMEONE_OFFER_HIGHER_THAN_YOURS",
    9 => "TRADEYA_IS_LIVE",
    10 => "RATE_OFFER",
    11 => "SEE_COMMENT",
    12 => "SEE_PUB_COMMENT",
    13 => "CONTACT_ALL",
    14 => "TRADEYA_POSTPONED",
    15 => "TRADEYA_RESUMED",
    16 => "YOUR_ACCOUNT_DEACTIVATED",
    17 => "OFFER_ON_TRADEYA_EDITED",
    18 => "OFFER_ON_TRADEYA_DELETED",
    19 => "OFFER_ACCEPTED",
    20 => "TRADEYA_COMPLETED",
    21 => "TRADEYA_POSTPONED_PUB",
    22 => "TRADEYA_REACTIVATED",
    23 => "WRITE_REVIEW",
    24 => "CATEGORY_MATCH",
    25 => "PERSON_MATCH",
    26 => "CONTEST_EMAIL",
    27 => "GUEST_UPGRADE_REMINDER",
    28 => "GUEST_FINAL_REMINDER",
    29 => "GUEST_FAREWELL",
    30 => "MOVING_ON"
}

CATEGORY_MATCH = 1
PERSON_MATCH = 2

MATCH_FINISH = 0
MATCH_PRESENT = 1
MATCH_CLEAR = 2

TRADEYA_MATCH_TYPE_BEST = 1
TRADEYA_MATCH_TYPE_MINIMUM = 2
TRADEYA_MATCH_TYPE_FINAL = 3

DID_NOT_WANT_MATCHED_ITEM = 1
DID_NOT_LIKE_MATCHED_PERSON = 2
MATCH_DID_NOT_MAKE_SENSE = 3
ALL_ABOVE_REASONS = 4

APP_PROP = {:landing_page => '/'}

# constants used in templates also need to be defined in the helper
USED_CONDITION = 1
NEW_CONDITION = 2

MEET_UP = 1
DELIVERY_ONLY = 2
PICK_UP_ONLY = 3
YOUR_PLACE = 4
MY_PLACE = 5
REMOTELY = 6

# Exchange Methods
I_WILL_BRING_IT_TO_YOU = 1
YOU_COME_GET_IT = 2
LET_US_MEET_UP = 3
I_WILL_SHIP_IT = 4